### ISSUE TITLE
Unable to save to png / svg with Selenium with chrome driver on Ubuntu 20.04 and Python 3.8.10

### ISSUE THREAD

**Issue by fconil** [altair-viz/altair_saver#101]
Hi everyone,

I am using selenium and I get a traceback when I try to save my chart to a png / svg file with chrome driver.

I get a `selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist` error

The chart is successfully saved with geckodriver.

The drivers are in my virtualenv "bin" folder, so they are in the path.

My code is the following : https://gist.github.com/fconil/b75c8eef479bb205ff226a13f0aeac62

I noticed there were many `DevToolsActivePort` issues on Selenium : https://github.com/SeleniumHQ/selenium/issues?q=is%3Aissue+DevToolsActivePort+is%3Aclosed

Regards

**Comment by jakevdp** [comment]
Sorry this isn't working for you.

https://stackoverflow.com/q/50642308 suggests that this might be due to running selenium as the root user, and can be remedied by running from another user account.

**Comment by fconil** [comment]
Fortunately, Firefox webdriver works :)

I am using Selenium 4.1.0 - (2).

Chrome binaries are installed by apt / snap  in `/snap/bin` and belong to root. This is not a problem for Firefox, I admit I am confused by this thread.

I did not found how to "run Chrome as a regular user", I may be missing something.

Now I am trying  to simply instantiate a chrome webdriver but I still get a `WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist` error message, so I have asked the Selenium project for an advice : https://github.com/SeleniumHQ/selenium/issues/10341.

Thanks Jake for your prompt reply and for your help.

**Comment by jakevdp** [comment]
I have to admit that selenium remains mostly mysterious to me. I cobbled together this package in a way that seems to work much of the time, but I apologize that I can't be of more help in debugging selenium issues.

**Comment by fconil** [comment]
I try to dig the Selenium / Chromium problem and I found some information that I shared in the Selenium issue : https://github.com/SeleniumHQ/selenium/issues/10341#issuecomment-1034006716

I noticed that on Ubuntu, Chromium was installed with a chromedriver (chromium.chromedriver) with Snap in `/snap/bin/`.

Unfortunately, it is not found automatically and I had to specify the executable_path.

Don't apologize, it is not an Altair issue in fact :)

**Comment by ehansis** [comment]
I just stumbled upon the same issue (`DevToolsActivePort file doesn't exist`). This indeed seems to be an issue with the Snap way of installing Chromium. I found some relevant information here: https://stackoverflow.com/a/65121582/5839193

What helped for me was adding an option `.add_argument('--user-data-dir=/home/me/foo')` to point the webdriver to use a different directory for its config files.

Using the original chromedriver installed with Snap didn't help but resulted in an error `Service chromedriver unexpectedly exited. Status code was: 64` (which I didn't investigate further).

All these are not really issues of `altair_saver`... but what would help is having some way of passing additional options to the Webdriver when it is being instantiated. If I'm not mistaken, there seems to be an open PR (#69) that has some code for that? Right now I'm resorting to hand-patching the respective file in altair_saver...

**Comment by joelostblom** [comment]
Since Altair 5.2, the functionality of Altair Saver is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package. Most of the functionality has been available since 5.0, and [the main addition in 5.2 was PDF export](https://github.com/altair-viz/altair/pull/3244). See [the docs on how to save charts](https://altair-viz.github.io/user_guide/saving_charts.html#png-svg-and-pdf-format) for more details

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for saving charts mentioned above and if you run into issues, please open an issue directly in the altair or vl-convert repo.
