### ISSUE TITLE
Appears with a lot of errors

### ISSUE THREAD

**Issue by aakhmetz** [altair-viz/altair_saver#111]
Hello, 

just wondering, why it works so unstable? I like the altair package, but saving is quite painful. The selenium backend gives an error with newer versions, the workaround with 4.2.0 version works not every time. For example, now it gives me the error about MaxRetries.

If I use the other backend, then 
```
vega-lite.js:740
      deepMerge_(dest, s ?? {});
                          ^

SyntaxError: Unexpected token '?'
```
or some other similar errors.

Overall, saving in any backend with either pdf or svg gives different errors.

**Comment by joelostblom** [comment]
The saving process has been significanlty improved in https://github.com/altair-viz/altair/pull/2701, which will be in the next release. In the meantime you can try downgrading selenium or using vl-convert manually:

```
import pandas as pd
import altair as alt


source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})
chart = alt.Chart(source).mark_bar().encode(
    x='a',
    y='b'
)


# Saving the chart
# First run `pip install vl-convert-python`
import vl_convert as vlc

png_data = vlc.vegalite_to_png(chart.to_dict())
with open("chart.png", "wb") as f:
    f.write(png_data)
```

**Comment by aakhmetz** [comment]
Thank you! It solved my problem and now it works quite well

(I did it for saving svg though)
```
def save_chart(chart_to_save, filename):
    svg_str = vlc.vegalite_to_svg(chart_to_save.to_json())
    with open(filename, "wt") as f:
        f.write(svg_str)
```
