### ISSUE TITLE
Saving by path to directory

### ISSUE THREAD

**Issue by Amarounek** [altair-viz/altair_saver#20]
Is there any command for saving figure to specific directory by path?

Thank you!

**Comment by jakevdp** [comment]
Yes, for example:

```
from altair_saver import save
save(chart, "path/to/specific/directory/chart.png")
```

**Comment by Amarounek** [comment]
Okey I solved it. I need to put r before path

```
from altair_saver import save
save(chart, r"path/to/specific/directory/chart.png")
```

**Comment by jakevdp** [comment]
That should only be necessary if your path contains unescapable special characters.

**Comment by jakevdp** [comment]
That is only necessary if your path contains unescaped special characters.

**Comment by Amarounek** [comment]
Okey maybe it is a little bit off-topic, however, how can I do something like this...

`save(graph, r'..\final climate reports\figures\fig_prec_1983_2020.svg')`

`FileNotFoundError: [Errno 2] No such file or directory: '..\\final climate reports\\figures\\fig_prec_1983_2020.svg'`

**Comment by jakevdp** [comment]
Try using forward slashes rather than backward slashes in your path, and also make sure the directories exist before attempting to create files in them.

**Comment by Amarounek** [comment]
Nope . Still not working. Directories exist, however still the same mistake.... Is it Altair_saver or my poor python skills? :/
I can probably use shutil.move() from the current directory...

**Comment by jakevdp** [comment]
All that's altair_saver does is to call Python's open() function on the path you supply. So any filepath you can write to from a standard Python function is one you should be able to save to.

**Comment by Amarounek** [comment]
So, It's my issue. :-) Okey I will try to solve it on my own. Anyway thank you very much for your willingness
