### ISSUE TITLE
Add option for passing additional logging options to vega (e.g., vg2svg)

### ISSUE THREAD

**Issue by boydgreenfield** [altair-viz/altair_saver#51]
Currently, it doesn't appear possible to pass arguments to `vg2svg` and `stderr` is being written directly into a notebook environment by [`check_output_with_stderr`](https://github.com/altair-viz/altair_saver/blob/e9e5cd6e63aed186433e0678ee8709ed7fe1e728/altair_saver/_utils.py#L170-L198). This also isn't suppressible as it's not a Python `warning`.

While it's possible subclass `NodeSaver` and `vg2svg`, well, it's a lot of work. As with `embed_options`, it'd be nice to be able to pass `vega_cli_options` or some similar list that would get passed through with the `cmd` into `subprocess.run`. 

Ideally, this would be settable on `alt.renderers.options` as with `embed_options` (or maybe not, I'm just spitballing on the implementation).

Concretely, the issue motivating all of this is that when you have multiple renderers enabled, e.g., `alt.renderers.enable("altair_saver", fmts=["html", "svg"])` you see warnings in your Jupyter notebook from the `svg` renderer shelling out to `vg2svg` (I _think_):

![image](https://user-images.githubusercontent.com/535969/77706768-85d44700-6f80-11ea-8c93-0608cfeccc9c.png)

**Comment by jakevdp** [comment]
A companion fix might be to display stderr from the vega CLI commands via Python warnings, so that they could be suppressed if desired.

**Comment by jakevdp** [comment]
I made an attempt at piping errors through warnings – it's not hard to implement, but I don't think the result are all that useful.

I think the best fix here is to add options as in #52, but also to unconditionally hide stderr outputs that match ``"WARN Can not resolve event source"``, as it sounds like these will appear any time you save a chart with interactive features using the CLI. I don't think these warnings will ever be useful to users, and it would be nice to hide them by default.
