### ISSUE TITLE
Running inside of a crontab

### ISSUE THREAD

**Issue by d-huck** [altair-viz/altair_saver#58]
Whenever I am running my code inside of a cron script, I get this error:

```
Traceback (most recent call last):
  File "/home/dhuck/projects/notebooks/COVID/update.py", line 466, in <module>
    main()
  File "/home/dhuck/projects/notebooks/COVID/update.py", line 456, in main
    save(world, world_file)
  File "/home/dhuck/projects/notebooks/.env/lib/python3.6/site-packages/altair_saver/_core.py", line 157
+, in save
    Saver = _select_saver(method, mode=mode, fmt=fmt, fp=fp)
  File "/home/dhuck/projects/notebooks/.env/lib/python3.6/site-packages/altair_saver/_core.py", line 72,
+in _select_saver
    raise ValueError(f"No enabled saver found that supports format={fmt!r}")
ValueError: No enabled saver found that supports format='vega'
```

This runs fine whenever I run the script as a user. I have added `export DISPLAY=:0;` before my script as [noted here](https://stackoverflow.com/questions/20575751/execute-python-selenium-script-in-crontab) to no avail. I am calling `altair_saver` like so:

```
world_file    = f'{PWD}/data/world_covid.vg.json'
save(world, world_file)
```

I attempted installing the nodeJS packages which resulted in a malformed chart.

**Comment by d-huck** [comment]
This was an issue with selenium, not `altair_saver`. If anyone else ends up on this issue, I solved it by setting up my crontab like so:

```
   SHELL=/bin/bash
   15 20 * * * PATH=$PATH:/usr/local/bin/:/usr/bin/:/usr/sbin/:/bin && export DISPLAY=:0 &&  /home/dhuck/altair_saver_script.sh
```
`altair-saver` wasn't able to detect that selenium and chromedriver are installed without having those inside the $PATH.

**Comment by jakevdp** [comment]
This is how altair_saver determines if selenium is available: https://github.com/altair-viz/altair_saver/blob/a4be53dad5df23d68f37f2bb9f0782ab79ef7c96/altair_saver/savers/_selenium.py#L99-L142

If this code raises an error, selenium is considered unavailable.

**Comment by halhenke** [comment]
I'm getting the same error - (not running inside a crontab - running from a jupyter notebook being served by a docker container) - i just copied and pasted that code into a notebook and what i found is the same thing noted in this comment from SO - for whatever reason, the "--no-sandbox" option has to be the first argument given to the webdriver. If "--headless" comes before "--no-sandbox" then it doesnt work.

https://stackoverflow.com/questions/53073411/selenium-webdriverexceptionchrome-failed-to-start-crashed-as-google-chrome-is#comment102570662_53073789

**Comment by jakevdp** [comment]
That should be a pretty straightforward fix; the relevant code is here: https://github.com/altair-viz/altair_saver/blob/fd19a884e2b12c2635813c46ec909a93100d8f90/altair_saver/savers/_selenium.py#L128-L135

Can you check whether rearranging those statements fixes the issue?

**Comment by jakevdp** [comment]
I'm rearranging the order in #59

**Comment by halhenke** [comment]
Hey - sorry for the delay in follow-up. I tested a bit more thoroughly and it seems that it was not the order of adding the options that was actually responsible for the problem in my case - it was the fact that the call to `os.geteuid` does not return 0 and so the flag is never added (i had stripped out the conditional block before).

Again, for context, this is being run from a Jupyter notebook being served from a Docker container. Hope that helps.

**Comment by jakevdp** [comment]
Can you help me understand why ``--no-sandbox`` is required in this case?
