### ISSUE TITLE
What's the best way to render pngs in notebook

### ISSUE THREAD

**Issue by birdsarah** [altair-viz/altair_saver#66]
I'm wondering what the best way is to setup altair to always render pngs.

I'm working in jupyter-lab.

I want my notebooks to be readable on github by default.

At the moment, I'm using this little show method:

```
import tempfile
from IPython.display import Image

def show(chart):
    file = tempfile.mktemp(suffix='.png')
    chart.save(file)
    return Image(file)
```

**Comment by jakevdp** [comment]
If you have [altair_saver](http://github.com/altair-viz/altair_saver) configured, you can use
```
alt.renderers.enable('png')
```
Another option is to use one of the frontend extension renderers in JupyterLab or Jupyter Notebook (see https://altair-viz.github.io/user_guide/display_frontends.html#displaying-in-jupyterlab); these will add a PNG to the output in the frontend, so no additional backend dependencies are necessary.

**Comment by birdsarah** [comment]
Thank you!

**Comment by jamesmyatt** [comment]
Where is `alt.renderers.enable('png')` described in the documentation?

**Comment by aborruso** [comment]
> Where is `alt.renderers.enable('png')` described in the documentation?

https://altair-viz.github.io/user_guide/display_frontends.html#altair-s-renderer-framework
