### ISSUE TITLE
Unable to save chart 

### ISSUE THREAD

**Issue by ibrahima12** [altair-viz/altair_saver#71]
Hi, 
I am saving svg's using altair_saver in my code, and up until a few minutes ago, everything was fine. But now I am getting the following error message: 

> No enabled saver found that supports format='svg'. 

Is there anything broken?

**Comment by jakevdp** [comment]
You'll have to make certain that altair_saver is installed, as well as either the selenium dependencies or the nodejs dependencies. See https://github.com/altair-viz/altair_saver#installation

**Comment by ibrahima12** [comment]
Hey Jake, 
I do have selenium installed, and altair_saver. Everything was going well until an hour ago for some reason. I had been using altair_saver since last weekend without issues. 
Here's the error message I get: 

>   File "/xxx/lib/python3.7/site-packages/altair_saver/_core.py", line 169, in save
>     Saver = _select_saver(method, mode=mode, fmt=fmt, fp=fp)
>   File "/xxx/lib/python3.7/site-packages/altair_saver/_core.py", line 69, in _select_saver
>     raise ValueError(f"No enabled saver found that supports format={fmt!r}")
> ValueError: No enabled saver found that supports format='svg'

**Comment by jakevdp** [comment]
Something on your system must have changed (chromedriver, maybe?) WHat happens if you run this?
```python
from selenium.webdriver import Chrome
driver = Chrome()
```

**Comment by ibrahima12** [comment]
Indeed: 

> selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81

My chromedriver version is 81.0.4044.69... but my Chrome version is 81.0.4044.138. I guess the difference in subversion matters? [Going to try updating chromedriver to the latest version and see if that fixes it].

**Comment by ibrahima12** [comment]
That fixed it! Thanks Jake and the team. I really enjoy using Altair :)
