### ISSUE TITLE
vega2png, vega2pdf, .. CLI commands

### ISSUE THREAD

**Issue by lukasheinrich** [altair-viz/altair_saver#78]
for command line tools producing vega json commands such as `vega2png` could be useful to produce visualizations from piped input. 

Something like this:
```
import sys 
import altair as alt
from altair_saver import save
infile = sys.stdin() if sys.argv[1]=="-" else open(sys.argv[1])
chart = alt.Chart.from_json(infile.read())
save(chart,sys.argv[2])
```

`curl http://... | vega2png - output.png` would seem quite useful. Is this in scope for this package?

**Comment by jakevdp** [comment]
Why not use the command line tools directly?

**Comment by lukasheinrich** [comment]
do they already exist? if so I must have missed them
